### ISSUE TITLE
Git and Github training

### ISSUE THREAD

**Issue by deobhushan88** [deobhushan88/fleaparking#1]
Ensure that everyone is familiar with using git and Github.

**Comment by GauravBhardwaj** [comment]
done... liked the idea of using git for project management as well as source control :)

**Comment by deobhushan88** [comment]
Cool :) 

Everyone, please take few minutes to go through this markdown training: https://guides.github.com/features/mastering-markdown/

Please reply here with questions on this training stuff, or reply DONE once you are done reading the above link, readme.md on the repo and the video sent on email. Then I'll close this.

**Comment by deobhushan88** [comment]
@amodrege @PrabhuSiddharth @GauravBhardwaj are you guys done with this?
- readme (and understood the git process)
- video
- markdown training

**Comment by praveendraniq** [comment]
Yeah **Bhushan** ! I am done with it :smile: 

| Topics | Status |
| --- | --- |
| MarkDown | Done |
| Readme | Done |
| Video | Done |

**Comment by deobhushan88** [comment]
Waiting for @amodrege to confirm
