### ISSUE TITLE
Set up test environment on the cloud

### ISSUE THREAD

**Issue by deobhushan88** [deobhushan88/fleaparking#3]
**Description**
Set up a test machine with a cloud service provider (such as Amazon) in order to test deployment of web services, database AND also a test service which returns test data for the app to consume.

**Acceptance Criteria**  
- [x] Cloud Service Provider Finalized (IaaS like Amazon, or some PaaS like Google, Heroku, etc...?)
- [x] Test Machine set up on the cloud
- [x] Test Service set up which returns test data for the app to consume. This services' endpoints correspond to those detailed in the API documentation.
- [x] URL and port on which this service runs provided to app developers.

**Comment by deobhushan88** [comment]
I also got the Github Education pack. So now have access for free to some cloud providers if any are suitable.
See here: https://education.github.com/pack

**Comment by GauravBhardwaj** [comment]
AWS, digitalOcean both can be used

**Comment by GauravBhardwaj** [comment]
Web and DB server are now setup in the SSD cloud(DigitalOcean) and are available for app developers. 
Test Service is also ready, instance URL and details will be mailed to team on demand.

**Comment by deobhushan88** [comment]
Test machine set up as per @GauravBhardwaj along with test endpoint. Closing
