### ISSUE TITLE
User login mechanism - 3rd party or own?

### ISSUE THREAD

**Issue by deobhushan88** [deobhushan88/fleaparking#42]
- The app will have user accounts. Users need to log in to their accounts to rent a parking space or rent out their own parking space, and also incoming and outgoing payments.
- Need to decide whether we want to use 3rd party login (login with google/facebook etc..), 3rd party login services (Amazon Cognito, Azure Active Directory etc.) or make our own login system.
- Also need to check out http://openid.net/developers/libraries/

**Comment by deobhushan88** [comment]
@PrabhuSiddharth Hi Prabhu, please research as per pointers in the description and give your findings, suggestions here.

**Comment by praveendraniq** [comment]
Yeah Bhushan. Sure. Will give my suggestions once I am done with my
research.

**Comment by deobhushan88** [comment]
Useful cheatsheets for securing web services: https://www.owasp.org/index.php/Cheat_Sheets

**Comment by praveendraniq** [comment]
Discussed and documented in the authentication endpoint on wiki: Google, basic auth
