### ISSUE TITLE
Use HTTPS for web services

### ISSUE THREAD

**Issue by deobhushan88** [deobhushan88/fleaparking#6]
**Description**  
Since the app and the backend needs to exchange information securely (username, password, payment info) we need to use HTTPS for web services.  

**Acceptance Criteria**
- [x] Completed research on how to make secure web services and use HTTPS.
- [ ] Findings posted on wiki and link left as a comment here.

**Comment by GauravBhardwaj** [comment]
Done. 
The backend team is now familiar with the way to include SSLin our web server (Python Bottle).

**Comment by deobhushan88** [comment]
Cool, are both you and @PrabhuSiddharth ready to work with Python? We have not discussed this option (python) with the professor in the past. Do you think that would be a problem?

**Comment by praveendraniq** [comment]
Yeah Bhushan.. Even I came to know that we are using python only yesterday.
It will certainly take some time for me to study and start with it. And
about professor, I have no idea. We should inform him in a formal mail and
hear what he says.

**Comment by deobhushan88** [comment]
Useful cheatsheets for securing web services: https://www.owasp.org/index.php/Cheat_Sheets

**Comment by deobhushan88** [comment]
Set up on test machine as per @GauravBhardwaj  Closing.
