### ISSUE TITLE
Change the app name from "Flea Parking" to "Parket"

### ISSUE THREAD

**Issue by deobhushan88** [deobhushan88/fleaparking#7]
**Description**
Change the app name from "Flea Parking" to "Parket" (Parking Market), which might be a more appealing name.

**Acceptance Criteria**
- [x] Name change discussed in comments and agreed.
- [x] Discuss and hopefully decide that this change does not mean that we need to change the name in 295B.

**Comment by deobhushan88** [comment]
Other suggestions from Prof.Zhang:
(1) Parkit
(2) ParkShare
(3) Parkware

My vote is for "Parket".

**Comment by deobhushan88** [comment]
@GauravBhardwaj @PrabhuSiddharth @amodrege Any opinions? I am going ahead with "Parket" for now for making the UI flows.

**Comment by praveendraniq** [comment]
I am Okay with "Parket" or "Parkit". Anything fine. I had a little concern
whether people would be aware of the term " flea Market" as we are using
"et" after Park. Would we be giving any naming justification with out App
icon or anywhere to insist??

**Comment by deobhushan88** [comment]
Proceeding with "Parket"
